// Generates the SDK's low-level transport types from the Developer API description
// (docs/api/openapi.json, itself generated from the API code). Run `pnpm sdk:generate`;
// a unit test fails when src/generated/openapi.ts is stale.
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

import openapiTS, { astToString } from 'openapi-typescript';

export const OPENAPI_FILE = fileURLToPath(
  new URL('../../../docs/api/openapi.json', import.meta.url),
);
export const GENERATED_FILE = fileURLToPath(
  new URL('../src/generated/openapi.ts', import.meta.url),
);

const HEADER = `/*
 * DO NOT EDIT — generated by \`pnpm sdk:generate\` (openapi-typescript) from
 * docs/api/openapi.json. Change the API (and regenerate its OpenAPI description)
 * instead; a test fails when this file is stale.
 */
/* eslint-disable */

`;

/** The generated TypeScript source for the current OpenAPI description. */
export async function generateSdkTypes() {
  const document = JSON.parse(await readFile(OPENAPI_FILE, 'utf8'));
  const ast = await openapiTS(document, {
    // Optional response fields stay optional; nullable fields stay `| null`.
    exportType: true,
    alphabetize: true,
  });
  return `${HEADER}${astToString(ast)}`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  await writeFile(GENERATED_FILE, await generateSdkTypes());
  process.stdout.write(`Wrote ${GENERATED_FILE}\n`);
}
